# Generated by Django 3.2.9 on 2021-11-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(upload_to='customer/'),
        ),
    ]
