# Generated by Django 3.2.9 on 2021-12-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_videoblog_play_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='designation',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='videoblog',
            name='title',
            field=models.TextField(),
        ),
    ]
