# Generated by Django 3.2.9 on 2021-12-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_marketingfeature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='class_name',
            field=models.CharField(default='abc', max_length=128),
            preserve_default=False,
        ),
    ]
