# Generated by Django 3.2.9 on 2021-12-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_product_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content_type',
            field=models.CharField(choices=[('blog_post', 'Blog post'), ('webinar', 'Webinar'), ('report', 'Report')], default='abc', max_length=128),
            preserve_default=False,
        ),
    ]
