# Generated by Django 3.2.9 on 2021-12-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_blog_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='link_text',
            field=models.CharField(default='abc', max_length=128),
            preserve_default=False,
        ),
    ]
