# Generated by Django 3.2.9 on 2021-12-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20211208_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(choices=[('1', 'United States'), ('2', 'Albania')], max_length=128),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_agreement',
            field=models.BooleanField(default=True),
        ),
    ]
