# Generated by Django 3.2.9 on 2021-12-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20211221_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='user_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
