# Generated by Django 3.2.9 on 2021-12-28 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_contact_user_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user_agreement',
        ),
    ]
