# Generated by Django 3.2.9 on 2021-12-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_contact_user_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
