# Generated by Django 3.2.9 on 2021-12-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_contact_user_agreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='whiteImage',
            field=models.FileField(default='ww', upload_to='customer/'),
            preserve_default=False,
        ),
    ]
