# Generated by Django 3.2.9 on 2021-12-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_customer_whiteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hero_image',
            field=models.ImageField(default=1, upload_to='product/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='q', max_length=128),
            preserve_default=False,
        ),
    ]
